version: "3.9"

services:
  db:
    build: ./db
    container_name: cinema_db_py
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema -d cinema"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: cinema_backend_py
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: cinema
      DB_PASSWORD: cinema
      DB_NAME: cinema
      BACKEND_PORT: "8000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: cinema_frontend_py
    environment:
      BACKEND_BASE_URL: http://backend:8000
      FLASK_RUN_PORT: "8080"
    depends_on:
      - backend
    ports:
      - "8080:8080"