
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinema-ms-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port: { number: 8080 }
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port: { number: 8080 }
    {{- else }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port: { number: 8080 }
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port: { number: 8080 }
    {{- end }}
