
apiVersion: v1
kind: Service
metadata:
  name: showtime
  namespace: {{ .Values.namespace }}
  labels: { app: showtime }
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: showtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showtime
  namespace: {{ .Values.namespace }}
  labels: { app: showtime }
spec:
  replicas: {{ .Values.showtime.replicas }}
  selector:
    matchLabels: { app: showtime }
  template:
    metadata:
      labels: { app: showtime }
      annotations:
        linkerd.io/inject: enabled
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["showtime"]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: showtime
          image: {{ .Values.showtime.image.repository }}:{{ .Values.showtime.image.tag }}
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 8000 } ]
          env:
            - name: DB_HOST
              value: postgres.{{ .Values.namespace }}.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "cinema"
            - name: DB_USER
              value: "showtime_user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet: { path: "/health", port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
{{ toYaml .Values.showtime.resources | indent 12 }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: showtime
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: showtime
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
